name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Start MySQL
      run: sudo systemctl start mysql
    - name: Set up MySQL database
      run: mysql --user=root --password=root --host 127.0.0.1 < src/main/resources/database.sql
    - name: Add sample data to MySQL database
      run: mysql --user=root --password=root --host 127.0.0.1 < src/main/resources/sample-data.sql
    - name: Create MySQL admin user to access database
      run: mysql --user=root --password=root --host 127.0.0.1 < src/main/resources/admin-user.sql
    - name: Build with Maven
      run: mvn -B package
    - name: Test with Maven
      run: mvn -B test
